# Generated by Django 4.1.5 on 2023-01-10 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
